
import { Translations } from './types';

export const DICTIONARY: Record<string, Translations> = {
    pt: {
        home: "Início",
        about: "Sobre",
        heroTitle: "Inovação & Excelência em Consultoria e Indústria",
        heroSubtitle: "A FlexiAura oferece soluções integradas em consultoria, desenvolvimento de software, negócios internacionais, logística e marketing. Fundada em 2025, nossa missão é transformar desafios em oportunidades de crescimento.",
        heroCta: "Entre em Contacto",
        servicesTitle: "Nossos Serviços",
        servicesSubtitle: "Oferecemos soluções especializadas para impulsionar o seu negócio em diversas áreas",
        platformsTitle: "Nossas Plataformas",
        platformsSubtitle: "A FlexiAura é detentora de diversas plataformas inovadoras que atendem a múltiplos setores",
        gamesTitle: "Área de Jogos",
        gamesSubtitle: "Relaxe e divirta-se com nossos jogos enquanto explora nossa plataforma",
        contactTitle: "Contacto & Informações",
        contactSubtitle: "Entre em contacto conosco para saber mais sobre nossos serviços e plataformas",
        snakeGame: "Jogo da Cobra",
        chessGame: "Xadrez",
        checkersGame: "Damas",
        candycrushGame: "Candy Crush",
        crossyroadGame: "Travessia",
        crossyroadInstructions: "Use as setas para mover o personagem. Evite carros e cruze a estrada com segurança!",
        startGame: "Iniciar Jogo",
        pauseGame: "Pausar",
        resetGame: "Reiniciar",
        score: "Pontuação",
        contactInfo: "GPS Condómino Bom Sossego, Camama, Luanda. Telefone: 929294029. Aberto de segunda a sexta das 8:30 às 16h. Aos sábados das 8 às 12h.",
        serviceTitle1: "Consultoria Empresarial",
        serviceDesc1: "Consultoria especializada em diversas áreas para otimizar processos, melhorar eficiência e maximizar resultados.",
        serviceTitle2: "Desenvolvimento de Software",
        serviceDesc2: "Criação de soluções tecnológicas personalizadas para atender às necessidades específicas do seu negócio.",
        serviceTitle3: "Negócios Internacionais",
        serviceDesc3: "Expansão global com estratégias de internacionalização, comércio exterior e parcerias internacionais.",
        serviceTitle4: "Logística e Supply Chain",
        serviceDesc4: "Otimização da cadeia de suprimentos, gestão de armazéns e soluções de distribuição eficientes.",
        serviceTitle5: "Marketing Digital",
        serviceDesc5: "Estratégias de marketing inovadoras para aumentar a visibilidade da marca e atrair clientes.",
        serviceTitle6: "Inovação e Transformação",
        serviceDesc6: "Implementação de tecnologias disruptivas e processos inovadores para manter sua empresa competitiva.",
        platformTitle1: "Fleximarket",
        platformDesc1: "Plataforma de e-commerce completa para negócios B2B e B2C.",
        platformTitle2: "Skillclone",
        platformDesc2: "Plataforma de desenvolvimento de habilidades profissionais com foco em certificação.",
        platformTitle3: "Flexilearn",
        platformDesc3: "Plataforma de educação online e cursos de aperfeiçoamento.",
        platformTitle4: "Flexistudios",
        platformDesc4: "Produção de conteúdo multimídia, incluindo vídeos e soluções de Realidade Virtual (VR).",
        platformTitle5: "Flexibet",
        platformDesc5: "Plataforma de entretenimento responsável e gestão de risco.",
        platformTitle6: "Kwanzapay",
        platformDesc6: "Soluções de pagamento digital e gestão de fluxos financeiros.",
        contactLocationTitle: "Localização",
        contactPhoneCardTitle: "Contacto",
        contactCoreBusinessTitle: "Core Business",
        locationAddressTitle: "Endereço",
        locationAddress: "GPS Condómino Bom Sossego, Camama, Luanda",
        locationHoursTitle: "Horário de Funcionamento",
        locationHours1: "Segunda a Sexta: 8:30 às 16:00",
        locationHours2: "Sábado: 8:00 às 12:00",
        contactPhoneTitle: "Telefone",
        contactEmailTitle: "Email",
        contactFoundedTitle: "Fundada em",
        coreBusiness1: "Consultoria em diversas áreas",
        coreBusiness2: "Desenvolvimento de softwares",
        coreBusiness3: "International business",
        coreBusiness4: "Logística",
        coreBusiness5: "Marketing",
        footerMission: "Consultoria & Indústria 2025. Transformando desafios em oportunidades através de soluções inovadoras e integradas.",
        footerServicesTitle: "Serviços",
        footerPlatformsTitle: "Plataformas",
        footerQuickLinksTitle: "Links Rápidos",
        copyright: "© 2025 FlexiAura Consultoria & Indústria. Todos os direitos reservados.",
        adText: "Patrocinado: Conheça nossas soluções de consultoria empresarial personalizadas para o seu setor. Entre em contacto para uma avaliação gratuita.",
        langButtonText: "Português",
        flexiStudiosTitle: "FlexiStudios - Produções",
        flexiStudiosSubtitle: "Explore o portfólio de vídeos e produções multimídia criados pela nossa divisão de estúdio.",
        aboutSectionTitle: "Sobre Nós",
        aboutDescription: "Fundada em 2025, a FlexiAura nasceu da necessidade de integrar consultoria estratégica com soluções tecnológicas de ponta. Operamos na interseção entre inovação industrial e desenvolvimento digital.",
        aboutMissionTitle: "Missão",
        aboutMissionDesc: "Capacitar empresas através de soluções integradas que simplificam processos complexos.",
        aboutVisionTitle: "Visão",
        aboutVisionDesc: "Ser referência global em consultoria e tecnologia.",
        quizTitle: "Teste seu Conhecimento",
        quizSubtitle: "Desafie a si mesmo com perguntas aleatórias em diferentes categorias",
        quizQuestion: "Pergunta",
        quizOf: "de",
        resetQuiz: "Reiniciar Quiz",
        submitAnswer: "Enviar Resposta",
        correctExclamation: "Correto!",
        incorrectExclamation: "Incorreto",
        nextQuestion: "Próxima Pergunta",
        restartQuiz: "Reiniciar Quiz",
        congrats: "Parabéns!",
        quizCompleteMsg: "Você completou todas as 50 perguntas! Clique em 'Reiniciar Quiz' para começar de novo com uma nova ordem.",
        loading: "Carregando...",
    },
    en: {
        home: "Home",
        about: "About Us",
        heroTitle: "Innovation & Excellence in Consulting and Industry",
        heroSubtitle: "FlexiAura offers integrated solutions in consulting, software development, international business, logistics and marketing. Founded in 2025, our mission is to transform challenges into growth opportunities.",
        heroCta: "Get in Touch",
        servicesTitle: "Our Services",
        servicesSubtitle: "We offer specialized solutions to boost your business in various areas",
        platformsTitle: "Our Platforms",
        platformsSubtitle: "FlexiAura owns several innovative platforms serving multiple sectors",
        gamesTitle: "Games Area",
        gamesSubtitle: "Relax and have fun with our games while exploring our platform",
        contactTitle: "Contact & Information",
        contactSubtitle: "Contact us to learn more about our services and platforms",
        snakeGame: "Snake Game",
        chessGame: "Chess",
        checkersGame: "Checkers",
        candycrushGame: "Candy Crush",
        crossyroadGame: "Crossy Road",
        crossyroadInstructions: "Use arrow keys to move the character. Avoid cars and cross the road safely!",
        startGame: "Start Game",
        pauseGame: "Pause",
        resetGame: "Reset",
        score: "Score",
        contactInfo: "GPS Condómino Bom Sossego, Camama, Luanda. Phone: 929294029. Open Monday to Friday from 8:30 to 16:00. Saturdays from 8:00 to 12:00.",
        serviceTitle1: "Business Consulting",
        serviceDesc1: "Specialized consulting in various areas to optimize processes, improve efficiency, and maximize results.",
        serviceTitle2: "Software Development",
        serviceDesc2: "Creation of customized technological solutions to meet the specific needs of your business.",
        serviceTitle3: "International Business",
        serviceDesc3: "Global expansion with internationalization strategies, foreign trade, and international partnerships.",
        serviceTitle4: "Logistics and Supply Chain",
        serviceDesc4: "Supply chain optimization, warehouse management, and efficient distribution solutions.",
        serviceTitle5: "Digital Marketing",
        serviceDesc5: "Innovative marketing strategies to increase brand visibility and attract customers.",
        serviceTitle6: "Innovation and Transformation",
        serviceDesc6: "Implementation of disruptive technologies and innovative processes to keep your company competitive.",
        platformTitle1: "Fleximarket",
        platformDesc1: "Complete e-commerce platform for B2B and B2C businesses.",
        platformTitle2: "Skillclone",
        platformDesc2: "Professional skills development platform focused on certification.",
        platformTitle3: "Flexilearn",
        platformDesc3: "Online education platform and advanced training courses.",
        platformTitle4: "Flexistudios",
        platformDesc4: "Multimedia content production, including videos and Virtual Reality (VR) solutions.",
        platformTitle5: "Flexibet",
        platformDesc5: "Responsible entertainment and risk management platform.",
        platformTitle6: "Kwanzapay",
        platformDesc6: "Digital payment solutions and financial flow management.",
        contactLocationTitle: "Location",
        contactPhoneCardTitle: "Contact",
        contactCoreBusinessTitle: "Core Business",
        locationAddressTitle: "Address",
        locationAddress: "GPS Condómino Bom Sossego, Camama, Luanda",
        locationHoursTitle: "Opening Hours",
        locationHours1: "Monday to Friday: 8:30 to 16:00",
        locationHours2: "Saturday: 8:00 to 12:00",
        contactPhoneTitle: "Phone",
        contactEmailTitle: "Email",
        contactFoundedTitle: "Founded in",
        coreBusiness1: "Consulting in various areas",
        coreBusiness2: "Software development",
        coreBusiness3: "International business",
        coreBusiness4: "Logistics",
        coreBusiness5: "Marketing",
        footerMission: "Consulting & Industry 2025. Transforming challenges into opportunities through innovative and integrated solutions.",
        footerServicesTitle: "Services",
        footerPlatformsTitle: "Platforms",
        footerQuickLinksTitle: "Quick Links",
        copyright: "© 2025 FlexiAura Consulting & Industry. All rights reserved.",
        adText: "Sponsored: Explore our personalized business consulting solutions for your sector. Contact us for a free evaluation.",
        langButtonText: "English",
        flexiStudiosTitle: "FlexiStudios - Productions",
        flexiStudiosSubtitle: "Explore the portfolio of videos and multimedia productions created by our studio division.",
        aboutSectionTitle: "About Us",
        aboutDescription: "Founded in 2025, FlexiAura was born from the need to integrate strategic consulting with cutting-edge technological solutions. We operate at the intersection of industrial innovation and digital development.",
        aboutMissionTitle: "Mission",
        aboutMissionDesc: "Empower companies through integrated solutions that simplify complex processes.",
        aboutVisionTitle: "Vision",
        aboutVisionDesc: "To be a global reference in consulting and technology.",
        quizTitle: "Test Your Knowledge",
        quizSubtitle: "Challenge yourself with random questions across different categories",
        quizQuestion: "Question",
        quizOf: "of",
        resetQuiz: "Reset Quiz",
        submitAnswer: "Submit Answer",
        correctExclamation: "Correct!",
        incorrectExclamation: "Incorrect",
        nextQuestion: "Next Question",
        restartQuiz: "Restart Quiz",
        congrats: "Congratulations!",
        quizCompleteMsg: "You've completed all 50 questions! Click 'Restart Quiz' to start over with a new random order.",
        loading: "Loading...",
    },
    fr: {
        home: "Accueil",
        about: "À Propos",
        heroTitle: "Innovation et Excellence en Conseil et Industrie",
        heroSubtitle: "FlexiAura propose des solutions intégrées en conseil, développement de logiciels, affaires internationales, logistique et marketing. Fondée en 2025, notre mission est de transformer les défis en opportunités de croissance.",
        heroCta: "Nous Contacter",
        servicesTitle: "Nos Services",
        servicesSubtitle: "Nous offrons des solutions spécialisées pour stimuler votre entreprise dans divers domaines",
        platformsTitle: "Nos Plateformes",
        platformsSubtitle: "FlexiAura possède plusieurs plateformes innovantes desservant de multiples secteurs",
        gamesTitle: "Espace de Jeux",
        gamesSubtitle: "Détendez-vous et amusez-vous avec nos jeux tout en explorant notre plateforme",
        contactTitle: "Contact et Informations",
        contactSubtitle: "Contactez-nous pour en savoir plus sur nos services et plateformes",
        snakeGame: "Jeu du Serpent",
        chessGame: "Échecs",
        checkersGame: "Dames",
        candycrushGame: "Candy Crush",
        crossyroadGame: "Traversée",
        crossyroadInstructions: "Utilisez les flèches pour déplacer le personnage. Évitez les voitures et traversez la route en toute sécurité !",
        startGame: "Démarrer le Jeu",
        pauseGame: "Pause",
        resetGame: "Redémarrer",
        score: "Score",
        contactInfo: "GPS Condómino Bom Sossego, Camama, Luanda. Téléphone : 929294029. Ouvert du lundi au vendredi de 8h30 à 16h. Le samedi de 8h à 12h.",
        serviceTitle1: "Conseil aux Entreprises",
        serviceDesc1: "Conseil spécialisé dans divers domaines pour optimiser les processus, améliorer l'efficacité et maximiser les résultats.",
        serviceTitle2: "Développement de Logiciels",
        serviceDesc2: "Création de solutions technologiques personnalisées pour répondre aux besoins spécifiques de votre entreprise.",
        serviceTitle3: "Affaires Internationales",
        serviceDesc3: "Expansion mondiale avec des stratégies d'internationalisation, commerce exterior e partenariats internationaux.",
        serviceTitle4: "Logistique et Chaîne d'Approvisionnement",
        serviceDesc4: "Optimisation de la chaîne d'approvisionnement, gestion des entrepôts et solutions de distribution efficaces.",
        serviceTitle5: "Marketing Numérique",
        serviceDesc5: "Stratégies de marketing innovantes pour augmenter la visibilidade da marca e attirer les clients.",
        serviceTitle6: "Innovation et Transformation",
        serviceDesc6: "Mise en œuvre de technologies de rupture et de processus innovants pour maintenir la compétitivité de votre entreprise.",
        platformTitle1: "Fleximarket",
        platformDesc1: "Plateforme de commerce électronique complète pour les entreprises B2B et B2C.",
        platformTitle2: "Skillclone",
        platformDesc2: "Plateforme de développement des compétences professionnelles axée sur la certification.",
        platformTitle3: "Flexilearn",
        platformDesc3: "Plateforme d'éducation en ligne et de cours de perfectionnement.",
        platformTitle4: "Flexistudios",
        platformDesc4: "Production de contenu multimédia, y compris des vidéos et des solutions de Réalité Virtuelle (RV).",
        platformTitle5: "Flexibet",
        platformDesc5: "Plateforme de divertissement responsable et de gestion des risques.",
        platformTitle6: "Kwanzapay",
        platformDesc6: "Solutions de paiement numérique et gestion des flux financiers.",
        contactLocationTitle: "Localisation",
        contactPhoneCardTitle: "Contact",
        contactCoreBusinessTitle: "Activité Principale",
        locationAddressTitle: "Adresse",
        locationAddress: "GPS Condómino Bom Sossego, Camama, Luanda",
        locationHoursTitle: "Heures d'Ouverture",
        locationHours1: "Du lundi au vendredi : 8h30 à 16h00",
        locationHours2: "Samedi : 8h00 à 12h00",
        contactPhoneTitle: "Téléphone",
        contactEmailTitle: "E-mail",
        contactFoundedTitle: "Fondée en",
        coreBusiness1: "Conseil dans divers domaines",
        coreBusiness2: "Développement de logiciels",
        coreBusiness3: "Affaires internationales",
        coreBusiness4: "Logistique",
        coreBusiness5: "Marketing",
        footerMission: "Conseil et Industrie 2025. Transformer les défis en opportunités grâce à des solutions innovantes et intégrées.",
        footerServicesTitle: "Services",
        footerPlatformsTitle: "Plateformes",
        footerQuickLinksTitle: "Liens Rápidos",
        copyright: "© 2025 FlexiAura Conseil et Industrie. Tous droits réservés.",
        adText: "Sponsorisé: Découvrez nos solutions de conseil d'entreprise personnalisées pour votre secteur. Contactez-nous pour une évaluation gratuite.",
        langButtonText: "Français",
        flexiStudiosTitle: "FlexiStudios - Productions",
        flexiStudiosSubtitle: "Découvrez le portefeuille de vidéos et de productions multimédias créées par notre division studio.",
        aboutSectionTitle: "À Propos",
        aboutDescription: "Fondée en 2025, FlexiAura est née de la nécessité d'intégrer le conseil stratégique à des solutions technologiques de pointe. Nous opérons à l'intersection de l'innovation industrielle et du développement numérique.",
        aboutMissionTitle: "Mission",
        aboutMissionDesc: "Autonomiser les entreprises grâce à des solutions intégrées qui simplifient les processus complexes.",
        aboutVisionTitle: "Vision",
        aboutVisionDesc: "Être une référence mondiale en matière de conseil et de technologie.",
        quizTitle: "Testez vos connaissances",
        quizSubtitle: "Mettez-vous au défi avec des questions aléatoires dans différentes catégories",
        quizQuestion: "Question",
        quizOf: "de",
        resetQuiz: "Réinitialiser le Quiz",
        submitAnswer: "Soumettre la réponse",
        correctExclamation: "Correct !",
        incorrectExclamation: "Incorrect",
        nextQuestion: "Question Suivante",
        restartQuiz: "Recommencer le Quiz",
        congrats: "Félicitations !",
        quizCompleteMsg: "Vous avez terminé les 50 questions ! Cliquez sur 'Recommencer le Quiz' pour recommencer avec un nouvel ordre.",
        loading: "Chargement...",
    },
    zh: {
        home: "首页",
        about: "关于",
        heroTitle: "咨询与行业卓越创新",
        heroSubtitle: "FlexiAura 提供咨询、软件开发、国际业务、物流和营销方面的集成解决方案。 成立于 2025 年，我们的使命是将挑战转化为增长机遇。",
        heroCta: "联系我们",
        servicesTitle: "我们的服务",
        servicesSubtitle: "我们提供专业的解决方案，推动您在各个领域的业务发展",
        platformsTitle: "我们的平台",
        platformsSubtitle: "FlexiAura 拥有多个服务于多个行业的创新平台",
        gamesTitle: "游戏区",
        gamesSubtitle: "在探索我们平台的同时放松身心，享受游戏的乐趣",
        contactTitle: "联系方式与信息",
        contactSubtitle: "联系我们，了解更多关于我们的服务和平台",
        snakeGame: "贪吃蛇游戏",
        chessGame: "国际象棋",
        checkersGame: "跳棋",
        candycrushGame: "糖果传奇",
        crossyroadGame: "过马路",
        crossyroadInstructions: "使用箭头键移动角色。避开汽车，安全过马路！",
        startGame: "开始游戏",
        pauseGame: "暂停",
        resetGame: "重新开始",
        score: "得分",
        contactInfo: "GPS Condómino Bom Sossego, Camama, Luanda. 电话: 929294029. 周一至周五: 8:30 至 16:00. 周六: 8:00 至 12:00.",
        serviceTitle1: "商业咨询",
        serviceDesc1: "各领域专业咨询，旨在优化流程、提高效率和最大化成果。",
        serviceTitle2: "软件开发",
        serviceDesc2: "创建定制化的技术解决方案，以满足您的业务特定需求。",
        serviceTitle3: "国际业务",
        serviceDesc3: "通过国际化战略、对外贸易和国际合作关系实现全球扩张。",
        serviceTitle4: "物流与供应链",
        serviceDesc4: "供应链优化、仓库管理和高效的分销解决方案。",
        serviceTitle5: "数字营销",
        serviceDesc5: "创新的营销策略，以提高品牌知名度和吸引客户。",
        serviceTitle6: "创新与转型",
        serviceDesc6: "实施颠覆性技术和创新流程，保持公司竞争力。",
        platformTitle1: "Fleximarket",
        platformDesc1: "面向 B2B 和 B2C 业务的完整电子商务平台。",
        platformTitle2: "Skillclone",
        platformDesc2: "专注于认证的专业技能发展平台。",
        platformTitle3: "Flexilearn",
        platformDesc3: "在线教育平台和高级培训课程。",
        platformTitle4: "Flexistudios",
        platformDesc4: "多媒体内容制作，包括视频和虚拟现实 (VR) 解决方案。",
        platformTitle5: "Flexibet",
        platformDesc5: "负责任的娱乐和风险管理平台。",
        platformTitle6: "Kwanzapay",
        platformDesc6: "数字支付解决方案和财务流管理。",
        contactLocationTitle: "地址",
        contactPhoneCardTitle: "联系方式",
        contactCoreBusinessTitle: "核心业务",
        locationAddressTitle: "地址",
        locationAddress: "GPS Condómino Bom Sossego, Camama, Luanda",
        locationHoursTitle: "营业时间",
        locationHours1: "周一至周五: 8:30 至 16:00",
        locationHours2: "周六: 8:00 至 12:00",
        contactPhoneTitle: "电话",
        contactEmailTitle: "电子邮件",
        contactFoundedTitle: "成立于",
        coreBusiness1: "各领域咨询",
        coreBusiness2: "软件开发",
        coreBusiness3: "国际业务",
        coreBusiness4: "物流",
        coreBusiness5: "营销",
        footerMission: "咨询与行业 2025。通过创新和集成解决方案，将挑战转化为机遇。",
        footerServicesTitle: "服务",
        footerPlatformsTitle: "平台",
        footerQuickLinksTitle: "快速链接",
        copyright: "© 2025 FlexiAura 咨询与行业。保留所有权利。",
        adText: "赞助：探索我们针对您所在行业的个性化商业咨询解决方案。 联系我们进行免费评估。",
        langButtonText: "中文",
        flexiStudiosTitle: "FlexiStudios - 制作",
        flexiStudiosSubtitle: "探索我们工作室部门制作的视频和多媒体作品集。",
        aboutSectionTitle: "关于我们",
        aboutDescription: "FlexiAura 成立于 2025 年，源于将战略咨询与尖端技术解决方案相结合的需求。 我们运作于工业创新与数字发展的交汇点。",
        aboutMissionTitle: "使命",
        aboutMissionDesc: "通过简化复杂流程的集成解决方案为企业赋能。",
        aboutVisionTitle: "愿景",
        aboutVisionDesc: "成为咨询和技术领域的全球参考。",
        quizTitle: "测试你的知识",
        quizSubtitle: "在不同类别中用随机问题挑战自己",
        quizQuestion: "问题",
        quizOf: "之",
        resetQuiz: "重置测验",
        submitAnswer: "提交答案",
        correctExclamation: "正确！",
        incorrectExclamation: "不正确",
        nextQuestion: "下一题",
        restartQuiz: "重新开始测验",
        congrats: "恭喜！",
        quizCompleteMsg: "您已完成所有 50 个问题！点击“重新开始测验”以新的随机顺序重新开始。",
        loading: "载入中...",
    },
    ar: {
        home: "الرئيسية",
        about: "من نحن",
        heroTitle: "الابتكار والتميز في الاستشارات والصناعة",
        heroSubtitle: "تقدم فليكسي أورا حلولاً متكاملة في الاستشارات، وتطوير البرمجيات، والأعمال الدولية، والخدمات اللوجستية، والتسويق. تأسست في عام 2025، ومهمتنا هي تحويل التحديات إلى فرص للنمو.",
        heroCta: "تواصل معنا",
        servicesTitle: "خدماتنا الأساسية",
        servicesSubtitle: "نقدم حلولاً متخصصة لدعم نمو عملك في مختلف المجالات",
        platformsTitle: "منصاتنا التقنية",
        platformsSubtitle: "تمتلك فليكسي أورا العديد من المنصات المبتكرة التي تخدم قطاعات متعددة",
        gamesTitle: "منطقة الألعاب",
        gamesSubtitle: "استرخ واستمتع بألعابنا أثناء استكشاف منصتنا",
        contactTitle: "الاتصال والمعلومات",
        contactSubtitle: "تواصل معنا لمعرفة المزيد عن خدماتنا ومنصاتنا",
        snakeGame: "لعبة الثعبان",
        chessGame: "الشطرنج",
        checkersGame: "لعبة الضامة",
        candycrushGame: "كاندي كراش",
        crossyroadGame: "عبور الطريق",
        crossyroadInstructions: "استخدم مفاتيح الأسهم لتحريك الشخصية. تجنب السيارات واعبر الطريق بأمان!",
        startGame: "بدء اللعبة",
        pauseGame: "إيقاف مؤقت",
        resetGame: "إعادة التشغيل",
        score: "النقاط",
        contactInfo: "GPS Condómino Bom Sossego, Camama, Luanda. الهاتف: 929294029. مفتوح من الاثنين إلى الجمعة من 8:30 إلى 16:00. السبت من 8:00 إلى 12:00.",
        serviceTitle1: "استشارات الأعمال",
        serviceDesc1: "استشارات متخصصة في مجالات مختلفة لتحسين العمليات، وزيادة الكفاءة، وتحقيق أقصى قدر من النتائج.",
        serviceTitle2: "تطوير البرمجيات",
        serviceDesc2: "إنشاء حلول تقنية مخصصة لتلبية الاحتياجات الخاصة لعملك.",
        serviceTitle3: "الأعمال الدولية",
        serviceDesc3: "توسع عالمي باستراتيجيات تدويل، وتجارة خارجية، وشراكات دولية.",
        serviceTitle4: "الخدمات اللوجستية وسلسلة الإمداد",
        serviceDesc4: "تحسين سلسلة الإمداد، وإدارة المستودعات، وحلول التوزيع الفعالة.",
        serviceTitle5: "التسويق الرقمي",
        serviceDesc5: "استراتيجيات تسويق مبتكرة لزيادة وضوح العلامة التجارية وجذب العملاء.",
        serviceTitle6: "الابتكار والتحول",
        serviceDesc6: "تنفيذ تقنيات رائدة وعمليات مبتكرة للحفاظ على قدرة شركتك التنافسية.",
        platformTitle1: "فليكسي ماركت",
        platformDesc1: "منصة تجارة إلكترونية كاملة للأعمال بين الشركات (B2B) وللمستهلك (B2C).",
        platformTitle2: "سكيل كلون",
        platformDesc2: "منصة تطوير المهارات المهنية مع التركيز على الاعتماد والشهادات.",
        platformTitle3: "فليكسي ليرن",
        platformDesc3: "منصة تعليم عبر الإنترنت ودورات تدريبية متقدمة.",
        platformTitle4: "فليكسي ستوديوز",
        platformDesc4: "إنتاج محتوى الوسائط المتعددة، بما في ذلك مقاطع الفيديو وحلول الواقع الافتراضي (VR).",
        platformTitle5: "فليكسي بت",
        platformDesc5: "منصة ترفيه مسؤولة وإدارة المخاطر.",
        platformTitle6: "كوانزا باي",
        platformDesc6: "حلول الدفع الرقمي وإدارة التدفقات المالية.",
        contactLocationTitle: "الموقع",
        contactPhoneCardTitle: "اتصال",
        contactCoreBusinessTitle: "الأنشطة الأساسية",
        locationAddressTitle: "العنوان",
        locationAddress: "GPS Condómino Bom Sossego, Camama, Luanda",
        locationHoursTitle: "ساعات العمل",
        locationHours1: "الاثنين إلى الجمعة: 8:30 إلى 16:00",
        locationHours2: "السبت: 8:00 إلى 12:00",
        contactPhoneTitle: "الهاتف",
        contactEmailTitle: "البريد الإلكتروني",
        contactFoundedTitle: "تأسست في",
        coreBusiness1: "استشارات في مجالات مختلفة",
        coreBusiness2: "تطوير البرمجيات",
        coreBusiness3: "الأعمال الدولية",
        coreBusiness4: "الخدمات اللوجستية",
        coreBusiness5: "التسويق",
        footerMission: "الاستشارات والصناعة 2025. تحويل التحديات إلى فرص من خلال حلول مبتكرة ومتكاملة.",
        footerServicesTitle: "الخدمات",
        footerPlatformsTitle: "المنصات",
        footerQuickLinksTitle: "روابط سريعة",
        copyright: "© 2025 فليكسي أورا للاستشارات والصناعة. جميع الحقوق محفوظة.",
        adText: "برعاية: اكتشف حلولنا الاستشارية للأعمال المخصصة لقطاعك. تواصل معنا لتقييم مجاني.",
        langButtonText: "العربية",
        flexiStudiosTitle: "فليكسي ستوديوز - للإنتاج",
        flexiStudiosSubtitle: "اكتشف مجموعة الفيديوهات والإنتاجات متعددة الوسائط التي أنشأها قسم الاستوديو لدينا.",
        aboutSectionTitle: "من نحن",
        aboutDescription: "تأسست فليكسي أورا في عام 2025، ونتجت عن الحاجة إلى دمج الاستشارات الاستراتيجية مع الحلول التقنية المتطورة. نحن نعمل عند تقاطع الابتكار الصناعي والتطوير الرقمي.",
        aboutMissionTitle: "المهمة",
        aboutMissionDesc: "تمكين الشركات من خلال حلول متكاملة تبسط العمليات المعقدة.",
        aboutVisionTitle: "الرؤية",
        aboutVisionDesc: "أن نكون مرجعاً عالمياً في الاستشارات والتكنولوجيا.",
        quizTitle: "اختبر معلوماتك",
        quizSubtitle: "تحدى نفسك بأسئلة عشوائية عبر فئات مختلفة",
        quizQuestion: "سؤال",
        quizOf: "من",
        resetQuiz: "إعادة تعيين الاختبار",
        submitAnswer: "إرسال الإجابة",
        correctExclamation: "صحيح!",
        incorrectExclamation: "غير صحيح",
        nextQuestion: "السؤال التالي",
        restartQuiz: "إعادة تشغيل الاختبار",
        congrats: "تهانينا!",
        quizCompleteMsg: "لقد أكملت جميع الأسئلة الخمسين! انقر فوق 'إعادة تشغيل الاختبار' للبدء من جديد بترتيب عشوائي جديد.",
        loading: "جار التحميل...",
    }
};